name: Test and Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8  

    - name: Run linting
      run: |
        flake8 . --max-line-length=100

    - name: Run tests
      run: |
        pytest